In [47]:
from bs4 import BeautifulSoup
import numpy as np
import pandas as pd

In [48]:
# Access folder

In [58]:
import os
from bs4 import BeautifulSoup

folder_path = r'D:\Main\Python Data Science cource\Web Scraping Projects\Glassdoor\all html'

company_names = []
rating = []
employer_size=[]
industry=[]
review=[]
salaries=[]
jobs=[]
location=[]
description=[]



for file_name in os.listdir(folder_path):
    file_path = os.path.join(folder_path, file_name)
    
    with open(file_path, 'r', encoding='utf-8') as f:
        html = f.read()

# Compnay_name columns

    soup = BeautifulSoup(html, 'html.parser')
    company_name_tags = soup.find_all('h2', {'data-test': 'employer-short-name'})
    
    for company_name_tag in company_name_tags:
        company_names.append(company_name_tag.text)

# Rating_column
    
  
    soup = BeautifulSoup(html, 'html.parser')
    html_content = soup.find_all('b')
    # Extract numerical values from <b> tags
    rating_list = [tag.text for tag in html_content if tag.text.replace('.', '', 1).isdigit()]
    rating.append(rating_list)
    
            
# Employer-size

        

    employer_size_spans = soup.find_all('span', {'class': 'd-block mt-0 css-56kyx5', 'data-test': 'employer-size'})

    # Iterate over the list of matching elements and access the text content
    for employer_size_span in employer_size_spans:
        employer_size_value = employer_size_span.text
        employer_size.append(employer_size_value)

# industry columns

    industry_spans = soup.find_all('span', {'class': 'd-block mt-0 css-56kyx5', 'data-test': 'employer-industry'})

    for industry_span in industry_spans:
        industry_value = industry_span.text
        industry.append(industry_value)        

 
# review_columns


    review_spans = soup.find_all('h3', {'class': 'mt-xsm mt-md-0', 'data-test': 'cell-Reviews-count'})

    for review_span in review_spans:
        review_value = review_span.text
        review.append(review_value)
        
        
# Salaries columns

    Salaries_spans = soup.find_all('h3', {'class': 'mt-xsm mt-md-0', 'data-test': 'cell-Salaries-count'})

    for Salaries_span in Salaries_spans:
        Salaries_value = Salaries_span.text
        salaries.append(Salaries_value)

# Jobs columns

    Jobs_spans = soup.find_all('h3', {'class': 'mt-xsm mt-md-0', 'data-test': 'cell-Jobs-count'})

    for Jobs_span in Jobs_spans:
        Jobs_value = Jobs_span.text
        jobs.append(Jobs_value)


# location columns

    location_spans = soup.find_all('span', {'class': 'd-block mt-0 css-56kyx5', 'data-test': 'employer-location'})

    for location_span in location_spans:
        location_value = location_span.text
        location.append(location_value)  
        

# # description column
  
#     new_spans = soup.find_all('p', {'class': 'css-1sj9xzx css-56kyx5'})
#     for new_span in new_spans:
#         new_value = new_span.text
#         if new_value =='':
#             description.append(new_value)
#         else:
#             description.append(np.nan)

In [59]:
# Using nested loops to access elements one by one
# making new columns for rating
rating_new=[]
for outer_list in rating:
    for element in outer_list:
        rating_new.append(element)

In [61]:
len(company_names),len(rating_new),len(employer_size),len(industry),len(review),len(salaries),len(jobs),len(location)

(3029, 3029, 3029, 3029, 3029, 3029, 3029, 3029)

In [63]:
# Making a daset for all columns


df = pd.DataFrame({
'company_names':company_names,
'rating_new':rating_new,
'employer_size':employer_size ,
'industry':industry,
'review':review,
'salaries':salaries,
'jobs':jobs,
'location':location 
})

In [64]:
df

,company_names,rating_new,employer_size,industry,review,salaries,jobs,location
0,Bajaj Allianz Life Insurance,3.8,1001 to 5000 Employees,Insurance Agencies & Brokerages,716,865,--,"Headquarters in Pune, India"
1,UltraTech Cement,3.9,10000+ Employees,Construction,818,788,--,"Ahura Centre,B‚ÄùWing, Mahakali Caves Road, Andh..."
2,Leo Burnett,3.6,1001 to 5000 Employees,Advertising & Public Relations,1.8T,246,318,5 office locations
3,Pramati Technologies,4.5,1001 to 5000 Employees,Enterprise Software & Network Solutions,662,618,--,5 office locations
4,Pernod Ricard,4.2,10000+ Employees,Food & Beverage Manufacturing,1.9T,220,267,19 office locations
...,...,...,...,...,...,...,...,...
3024,Unilever,4.1,10000+ Employees,Consumer Product Manufacturing,16.4T,1.9T,858,25 office locations
3025,GlobalLogic,3.8,10000+ Employees,Information Technology Support Services,7.1T,5.1T,720,49 office locations
3026,Reliance Industries,3.9,10000+ Employees,Energy & Utilities,6.6T,7T,46,25 office locations
3027,Flipkart,3.9,10000+ Employees,Internet & Web Services,5.6T,7.7T,77,10 office locations
3028,Shell,4.1,10000+ Employees,Energy & Utilities,14.2T,2.3T,699,31 office locations

In [65]:
df.to_csv('dataset.csv')